name: 🧹 Padronização de Código (Flake8)
 
on: [push]
 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Instalar Flake8
        run: pip install flake8
        
      - name: Analisar código
        # Verifica erros de sintaxe ou variáveis não usadas
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
